# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_candidate_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentpoll',
            name='votescast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentpoll',
            name='votesinvalid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentpoll',
            name='votesvalid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentvote',
            name='weight',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
