# Generated by Django 2.2.14 on 2020-07-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_remove_deprecated_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpoll',
            name='voting_principle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
