# Generated by Django 2.2.14 on 2020-07-31 16:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_rename_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_weight_2',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_weight_3',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_weight_4',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_weight_5',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0'), max_digits=15),
        ),
    ]
