# Generated by Jochen Winzer on 2020-11-23 13:29

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from openslides.users.models import Group


def add_navigate_permission(apps, schema_editor):
    """
    Adds the permission `can_navigate` to default, staff and committees group.
    """
    Projector = apps.get_model("core", "Projector")

    content_type = ContentType.objects.get_for_model(Projector)
    try:
        perm = Permission.objects.get(
            content_type=content_type, codename="can_navigate"
        )
    except Permission.DoesNotExist:
        perm = Permission.objects.create(
            codename="can_navigate",
            name="Can navigate",
            content_type=content_type,
        )

    try:
        default = Group.objects.get(name="Default")
        default.permissions.add(perm)
        default.save(skip_autoupdate=True)
    except Group.DoesNotExist:
        pass

    try:
        staff = Group.objects.get(name="Staff")
        staff.permissions.add(perm)
        staff.save(skip_autoupdate=True)
    except Group.DoesNotExist:
        pass

    try:
        committees = Group.objects.get(name="Committees")
        committees.permissions.add(perm)
        committees.save(skip_autoupdate=True)
    except Group.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_autopilot_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projector',
            options={
                'default_permissions': (),
                'permissions': (
                    ('can_see_projector', 'Can see the projector'),
                    ('can_manage_projector', 'Can manage the projector'),
                    ('can_see_frontpage', 'Can see the front page'),
                    ('can_see_livestream', 'Can see the live stream'),
                    ('can_see_autopilot', 'Can see the autopilot'),
                    ('can_navigate', 'Can navigate'),
                )
            },
        ),
        migrations.RunPython(add_navigate_permission)
    ]
