# Generated by Django 2.2.16 on 2020-12-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_vote_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keypad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
