# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0002_misc_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpoll',
            name='votescast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motionpoll',
            name='votesinvalid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motionpoll',
            name='votesvalid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motionvote',
            name='weight',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
